dataset_str:
  "OPV2VCoopCylindricalDataset(
    split='${dataset.opv2v.train.split}',
    ROOT='${dataset.opv2v.images_root}',
    depth_root='${dataset.opv2v.depth_root}',
    camera_ids=${dataset.opv2v.camera_ids},
    num_views=${dataset.num_views},
    variable_num_views=${dataset.train.variable_num_views},
    resolution=${dataset.opv2v.train.dataset_resolution},
    principal_point_centered=${dataset.principal_point_centered},
    transform='${dataset.opv2v.train.transform}',
    data_norm_type='${dataset.opv2v.train.data_norm_type}',
    aug_crop=${dataset.opv2v.train.aug_crop},
    seed=${dataset.opv2v.train.seed},
    max_num_retries=${dataset.opv2v.train.max_num_retries},
    min_agents=${dataset.opv2v.train.min_agents},
    min_num_views=${dataset.opv2v.train.min_num_views},
    max_num_views=${dataset.opv2v.train.max_num_views},
    panorama_resolution=${dataset.opv2v.train.panorama_resolution},
    panorama_vertical_fov_deg=${dataset.opv2v.train.panorama_vertical_fov_deg},
    panorama_elevation_center_deg=${dataset.opv2v.train.panorama_elevation_center_deg},
    view_selection_margin=${dataset.opv2v.train.view_selection_margin},
    max_scenes=${dataset.opv2v.train.max_scenes})"
split: ${dataset.opv2v.split_names.train}
dataset_resolution: ${dataset.opv2v.train.panorama_resolution}
transform: 'colorjitter+grayscale+gaublur'
data_norm_type: ${model.data_norm_type}
aug_crop: 16
seed: 777
max_num_retries: 5
min_agents: 4
min_num_views: 2
max_num_views: 4
max_scenes: null
panorama_resolution: [1008, 252]
panorama_vertical_fov_deg: 90.0
panorama_elevation_center_deg: 0.0
view_selection_margin: 0.05
